### ISSUE TITLE
New Match notifications not working?

### ISSUE THREAD

**Issue by brampower** [ncla/LoungeDestroyer#179]
The last couple of days (maybe even weeks?) I have not received a single 'new match' notification! I checked my settings and I definitely have it enabled. 

Is this a known issue or am I doing something wrong?
I already tried reinstalling the addon.

**Comment by ncla** [comment]
This has been broken since December release (if you installed or reinstalled extension) where a bug fix created a new bug. It is already fixed and the fix is in the repository.

You can fix the issue yourself however, or download extension from github..

https://www.reddit.com/r/loungedestroyer/comments/2ujwsx/notifications_not_working/?sort=confidence

**Comment by ncla** [comment]
This has been broken since December release where a bug fix created a new
bug. It is already fixed and the fix is in the repository.

You can fix the issue yourself however, or download extension from github..

https://www.reddit.com/r/loungedestroyer/comments/2ujwsx/notifications_not_working/?sort=confidence

**Comment by brampower** [comment]
Nice, thank you very much!
