### ISSUE TITLE
Auto-refresh "Please Wait" page after game ends

### ISSUE THREAD

**Issue by Pixstrad** [ncla/LoungeDestroyer#180]
After games end an item draft can take some time. My proposal is to add an auto-refresh to the extension that refreshes the page until "Please wait" etc. is gone.

Just an idea, any opposing remarks or support welcome!

Great extension, love it. :)

**Comment by ncla** [comment]
Wait.html redirect blocker was added because the redirect was annoying, the
site forced you onto another page where the top navigation had only links
to homepage..

Recently they finally removed it after very long time of them not
understanding how shit is.

Though I feel refreshing anymore is unnecessary, especially for maintenance
pages or 'we are being flooded' error pages since it creates the user
driven DDoS even more.

We might readd it as a disabled feature by default, but I don't really feel
like. I at least don't want to degrade server performance, you gotta be
careful with 115k (and growing ) user base, you know.

Maybe @birjolaxew thinks otherwise.

**Comment by Pixstrad** [comment]
That makes a whole ton of sense. :) It's honestly not that big of a deal to refresh the page a few times, I just thought it might be a convenience factor more than anything. But yeah, CSGOL's servers are overloaded as is, I suppose adding this extra bit of load is largely unnecessary.

**Comment by birjolaxew** [comment]
I re-implemented this in b619991.
