### ISSUE TITLE
Implement reload-free queue replacement

### ISSUE THREAD

**Issue by birjolaxew** [ncla/LoungeDestroyer#194]
So we don't have to reload the page every. single. time auto-bet is successful (and therefore no longer have to keep track of whether a stream is playing)

**Comment by ncla** [comment]
How I fixed it: I track the tab ID from where the auto-betting was initiated, once a bet was successful, it will attempt to refresh the previously said tab, if it no longer exists, a new one will be opened.

Not the best fix, but it works.

Alternatively we could check /mybets page because it also contains the trade offer button, security code, bot name etc.
