### ISSUE TITLE
Get rid of non standard timezone method within application

### ISSUE THREAD

**Issue by ncla** [ncla/LoungeDestroyer#197]
http://code.google.com/p/v8/issues/detail?id=3785

**Comment by birjolaxew** [comment]
Fixed in #189

**Comment by ncla** [comment]
Might use this instead, which depends on timezone offset instead.

https://github.com/Canop/tzdetect.js
http://dystroy.org/stackoverflow/timezonedetect.html

0.1s though. :^)
![](http://puu.sh/gV717/3f95528cfc.png)

**Comment by birjolaxew** [comment]
It's actually "only" ~53 ms. measured using `console.time`. That being said, it's still slow, mostly because they recompute the timezone index every time.

[This](https://gist.github.com/birjolaxew/d5ecaa76674982019a6e) is a much faster version. Has a first-run cost of ~14 ms., whereafter all matches are simple lookups (at ~0.1 ms. pr. match). It relies on moment.js' own `_offset` attribute though, which finds every single timezone the original tzdetect.js does, plus some.

**Comment by ncla** [comment]
![](http://puu.sh/h1utz/2398ac4da8.png)
First test is [this](https://github.com/Canop/tzdetect.js), 2nd test is improvement of first one by @birjolaxew, 3rd one is [jstz library](https://bitbucket.org/pellepim/jstimezonedetect)
