### ISSUE TITLE
Selecting items but not selecting a team does not display an error when betting

### ISSUE THREAD

**Issue by Fiskie** [ncla/LoungeDestroyer#230]
Easy to reproduce on CSGL. It threw me off when trying to place a bet; and I think a visible warning is necessary because it confused me for a little while. CSGL's betting interface does not distinguish between an unselected and a selected team very well.

I would have submitted a PR to fix this but the contribution guide said to open an issue first, so whatever.

**Comment by ncla** [comment]
Hey,

I mainly wrote that 'open issue before submitting PR' intended for new features only, it's fine for bug fixes to submit PR right away.

This seems like an issue CS:GO Lounge recently is experiencing where some assets are not loading for the user (scripts/images/stylesheet) because of CDN issues. Are you sure this is not the case? I do get an error if I haven't selected a team.

![](http://i.imgur.com/XcfLzt8.png)

**Comment by Fiskie** [comment]
That's a bit odd. It might've been. I can't reproduce it anymore.

I'll attribute it to CSGL being funky, then. Sorry.
