### ISSUE TITLE
Dota prices inaccurate if not base-quality

### ISSUE THREAD

**Issue by HarryS** [ncla/LoungeDestroyer#332]
Hi,

On Dota2Lounge, LD seems to get the prices inaccurately if they are of a different [Quality](http://dota2.gamepedia.com/Quality) than the default.

For example, it shows the value of [**Elder** Announcer: Death Prophet](http://steamcommunity.com/market/listings/570/Elder%20Announcer:%20Death%20Prophet) as that of the [base quality item].
(http://steamcommunity.com/market/listings/570/Announcer:%20Death%20Prophet)
![2016-03-08_16-14-05](https://cloud.githubusercontent.com/assets/627735/13605791/7d4da556-e549-11e5-98bd-af98b2cf08b8.png)

This happens on all items that are not of base quality. Not sure if it can be fixed easily, but would be nice. Thanks!

**Comment by ncla** [comment]
Hello,

Are you using cached prices or prices from Steam directly?

**Comment by ncla** [comment]
Okay it seems you are using cached item price lists, though I cannot find Elder Announcer Death Prophet on the site.

**Comment by ncla** [comment]
Bug is happening because DOTA2 Lounge sets incorrect alt tags for images, which is where we consistently get item names from.

![](http://i.imgur.com/Y1lg0zt.png)

Your best bet is to message admins through modmail. This is not something I want to fix from my side. https://www.reddit.com/r/csgolounge/
