### ISSUE TITLE
Remove stream option?

### ISSUE THREAD

**Issue by x64architecture** [ncla/LoungeDestroyer#335]
I would be nice if lounge destroyer had the option to remove the stream from the match page.

I see #98 but its not in the code anymore.

(I did it by removing the stream div)
https://github.com/x64architecture/LoungeDestroyer/commit/2ec2fe7ba17b045b1deb7f9de7189231236e9bbe

**Comment by ncla** [comment]
Hello,

The reason it was removed is because the admins kind of implied that removing stream affects viewership, that was particularly true when it was enabled, removing streams without any feedback.

It was probably removed entirely because I think I was asked to remove it, and I didn't mind, because LoungeDestroyer's functionality is to enhance experience and add additional features. Removing part of site would mean that we would have to add 'remove x' for other things as well, such as removing ads, removing social share links on match pages and so on. That is a task an ad-blocker should do. Same goes for things such as enforcing HTTPS on the site, extension 'HTTPS everywhere' will do that if that's your thing.

**Comment by x64architecture** [comment]
Yea I figured it was a task for an ad blocking rule. Thanks for the detailed reply though.
